apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: index-pod
  template:
    metadata:
      labels:
        app: index-pod
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: nginx-html

---
apiVersion: v1
kind: Service
metadata:
  name: index-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: index-pod
