apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: index-pod
  template:
    metadata:
      labels:
        app: index-pod
    spec:
      containers:
        - name: index
          image: nginx:alpine
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: index-service
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: index-pod
